version: "3.9"

services:
  # Dagster
  dagster:
    build:
      context: ./configs/dagster
      dockerfile: Dockerfile
    container_name: dagster
    image: dagster:latest

  # Dagster dagit: web interface
  dagster_dagit:
    depends_on:
      - dagster_postgres
    image: dagster:latest
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3001"
      - -w
      - workspace.yaml
    container_name: dagster_dagit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/dagster:/opt/dagster/dagster_home
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    networks:
      - network

  # Dagster daemon: Schedule and orchestrate pipeline executions
  dagster_daemon:
    image: dagster:latest
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/dagster:/opt/dagster/dagster_home
    env_file:
      - ./.env
    networks:
      - network

  # Postgres for Dagster
  dagster_postgres:
    build:
      context: ./configs/postgres/dagster
      dockerfile: Dockerfile
    container_name: dagster_postgres
    image: dagster_postgres:latest
    volumes:
      - ./configs/postgres/dagster:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - network

  # Data pipeline
  # pipeline:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile

networks:
  network:
    driver: bridge
    name: network
