services:

  ###################################################################### DAGSTER ######################################################################
  # Dagster
  dagster:
    image: dagster:latest
    build:
      context: ./configs/dagster
      dockerfile: Dockerfile
    container_name: dagster

  # Dagster dagit: web interface
  dagster_dagit:
    image: dagster:latest
    container_name: dagster_dagit
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/dagster/dagster_home:/opt/dagster/dagster_home
    env_file:
      - ./.env
    networks:
      - net
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3001"
      - -w
      - workspace.yaml
    deploy:
      resources:
        limits:
          memory: 8g

  # Dagster daemon: Schedule and orchestrate pipeline executions
  dagster_daemon:
    image: dagster:latest
    container_name: dagster_daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/dagster/dagster_home:/opt/dagster/dagster_home
    env_file:
      - ./.env
    networks:
      - net
    entrypoint:
      - dagster-daemon
      - run
    deploy:
      resources:
        limits:
          memory: 8g

  ###################################################################### PIPELINES ######################################################################
  # Data ETL Pipeline
  pipeline:
    image: pipeline:latest
    build:
      context: ./src/data/pipeline
      dockerfile: Dockerfile
    container_name: pipeline
    user: root
    ports:
      - "4000:4000"
    volumes:
      - ./src/data/pipeline:/opt/dagster/app
    env_file:
      - ./.env
    networks:
     - net
    depends_on:
     - dagster_dagit
     - dagster_daemon
    deploy:
      resources:
        limits:
          memory: 8g

  # Pipeline for materializing offline store into online store
  mtl_pipeline:
    image: mtl_pipeline:latest
    build:
      context: ./src/data/mtl_pipeline
      dockerfile: Dockerfile
    container_name: mtl_pipeline
    user: root
    ports:
      - "4001:4001"
    volumes:
      - ./src/data/mtl_pipeline:/opt/dagster/app
    env_file:
      - ./.env
    networks:
      - net
    depends_on:
     - dagster_dagit
     - dagster_daemon
    deploy:
      resources:
        limits:
          memory: 8g

  # Pipeline for training model
  training_pipeline:
    image: training_pipeline:latest
    build:
      context: ./src/data/training_pipeline
      dockerfile: Dockerfile
    container_name: training_pipeline
    user: root
    ports:
      - "4002:4002"
    volumes:
      - ./src/data/training_pipeline:/opt/dagster/app
    env_file:
      - ./.env
    networks:
     - net
    depends_on:
     - dagster_dagit
     - dagster_daemon
    deploy:
      resources:
        limits:
          memory: 8g

  # Pipeline for model serving
  model_serving:
    image: model_serving:latest
    build:
      context: ./src/data/model_serving
      dockerfile: Dockerfile
    container_name: model_serving
    user: root
    ports:
      - "4003:4003"
    volumes:
      - ./src/data/model_serving:/opt/dagster/app
    env_file:
      - ./.env
    networks:
      - net
    depends_on:
     - dagster_dagit
     - dagster_daemon
    deploy:
      resources:
        limits:
          memory: 8g

  ###################################################################### MINIO ######################################################################
  # Minio server for data storage
  minio_server:
    image: minio_server:latest
    build:
      context: ./configs/minio/server
      dockerfile: Dockerfile
    container_name: minio_server
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./logs/minio:/data
    env_file:
      - ./.env
    networks:
      - net
    command: ["server", "/data", "--console-address", ":9001"]
    deploy:
      resources:
        limits:
          memory: 4g

  # Minio client for UNIX command
  minio_client:
    image: minio_client:latest
    build:
      context: ./configs/minio/client
      dockerfile: Dockerfile
    container_name: minio_client
    hostname: mc
    env_file:
      - ./.env
    networks:
      - net
    depends_on:
      - minio_server
    entrypoint: /bin/sh -c "until (/usr/bin/mc config host add minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}); do echo '...waiting...' && sleep 1; done; /usr/bin/mc mb minio/${MINIO_BUCKET}; /usr/bin/mc policy set public minio/${MINIO_BUCKET}; /usr/bin/mc mb minio/${MLFLOW_BUCKET}; /usr/bin/mc policy set public minio/${MLFLOW_BUCKET}; exit 0;"
    deploy:
      resources:
        limits:
          memory: 4g

  ###################################################################### DATABASES ######################################################################
  # Postgres for Dagster
  dagster_postgres:
    image: dagster_postgres:latest
    build:
      context: ./configs/postgres/dagster
      dockerfile: Dockerfile
    container_name: dagster_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./logs/dagster_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${DAGSTER_POSTGRES_HOST}
      POSTGRES_PORT: ${DAGSTER_POSTGRES_PORT}
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

  # Postgres for Feast offline store
  feast_postgres:
    image: feast_postgres:latest
    build:
      context: ./configs/postgres/feast
      dockerfile: Dockerfile
    container_name: feast_postgres
    ports:
      - "5433:5432"
    volumes:
      - ./logs/feast_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${FEAST_POSTGRES_DB}
      POSTGRES_USER: ${FEAST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FEAST_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${FEAST_POSTGRES_HOST}
      POSTGRES_PORT: ${FEAST_POSTGRES_PORT}
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

  # Redis for Feast online store
  feast_redis:
    image: feast_redis:latest
    build:
      context: ./configs/redis
      dockerfile: Dockerfile
    container_name: feast_redis
    ports:
      - "6379:6379"
    volumes:
      - ./logs/feast_redis:/data
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

  # Postgres for MLflow
  mlflow_postgres:
    image: mlflow_postgres:latest
    build:
      context: ./configs/postgres/mlflow
      dockerfile: Dockerfile
    container_name: mlflow_postgres
    ports:
      - "5434:5432"
    volumes:
      - ./logs/mlflow_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${MLFLOW_POSTGRES_HOST}
      POSTGRES_PORT: ${MLFLOW_POSTGRES_PORT}
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

  sonarqube_postgres:
    image: sonarqube_postgres:latest
    build:
      context: ./configs/postgres/sonarqube
      dockerfile: Dockerfile
    container_name: sonarqube_postgres
    ports:
    - "5435:5432"
    volumes:
      - ./logs/sonarqube_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SONARQUBE_POSTGRES_DB}
      POSTGRES_USER: ${SONARQUBE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SONARQUBE_POSTGRES_PASSWORD}
      POSTGRES_HOST: ${SONARQUBE_POSTGRES_HOST}
      POSTGRES_PORT: ${SONARQUBE_POSTGRES_PORT}
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

  ###################################################################### MODEL TRACKING AND REGISTRY ######################################################################
  # MLFlow
  mlflow:
    image: mlflow:latest
    build:
      context: ./configs/mlflow
      dockerfile: Dockerfile
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      # - mlflow_artifacts:/mlflow/artifacts
      - ./logs/mlflow:/mlflow/mlruns
    environment:
      MLFLOW_TRACKING_SQL_ALCHEMY_CONN: postgresql://${MLFLOW_POSTGRES_USER}:${MLFLOW_POSTGRES_PASSWORD}@${MLFLOW_POSTGRES_HOST}:${MLFLOW_POSTGRES_PORT}/${MLFLOW_POSTGRES_DB}
      MLFLOW_TRACKING_URI: ${MLFLOW_ENDPOINT_URL}
      MLFLOW_S3_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MLFLOW_S3_IGNORE_TLS: true
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    env_file:
      - ./.env
    networks:
      - net
    depends_on:
      - mlflow_postgres
      - minio_server
      - minio_client
    command: >
      mlflow server
      --backend-store-uri postgresql://${MLFLOW_POSTGRES_USER}:${MLFLOW_POSTGRES_PASSWORD}@${MLFLOW_POSTGRES_HOST}:${MLFLOW_POSTGRES_PORT}/${MLFLOW_POSTGRES_DB}
      --host 0.0.0.0
      --serve-artifacts
      --artifacts-destination s3://artifacts
    deploy:
      resources:
        limits:
          memory: 4g

  ###################################################################### TEST ######################################################################
  # Jupyter notebook for experiment
  jupyter_notebook:
    image: jupyter_notebook:latest
    build:
      context: ./configs/jupyter
      dockerfile: Dockerfile
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./logs/jupyter_notebook:/home/jovyan/logs
      - ./src/data/mtl_pipeline/feature_repo:/home/jovyan/feature_repo
      - ./src/jupyter:/home/jovyan
      # - mlflow_artifacts:/mlflow/artifacts
    environment:
      MLFLOW_TRACKING_SQL_ALCHEMY_CONN: postgresql://${MLFLOW_POSTGRES_USER}:${MLFLOW_POSTGRES_PASSWORD}@${MLFLOW_POSTGRES_HOST}:${MLFLOW_POSTGRES_PORT}/${MLFLOW_POSTGRES_DB}
      MLFLOW_TRACKING_URI: ${MLFLOW_ENDPOINT_URL}
      MLFLOW_S3_ENDPOINT_URL: ${MINIO_ENDPOINT_URL}
      MLFLOW_S3_IGNORE_TLS: true
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    env_file:
      - ./.env
    networks:
      - net
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    deploy:
        resources:
          limits:
            memory: 4g

  ###################################################################### OPERATION ######################################################################
  jenkins:
    image: jenkins:latest
    build:
      context: ./configs/jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./logs/jenkins_home:/var/jenkins_home
      - .:/var/jenkins_home/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "4.0"
    restart: always

  ###################################################################### CODE ANALYSIS ######################################################################
  # Code Analysis
  sonarqube:
    image: sonarqube:latest
    build:
      context: ./configs/sonarqube
      dockerfile: Dockerfile
    container_name: sonarqube
    ports:
      - "9095:9000"
    volumes:
      - ./logs/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./logs/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./logs/sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - .:/opt/sonarqube/mlops_platform
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_postgres:5432/${SONARQUBE_POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${SONARQUBE_POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${SONARQUBE_POSTGRES_PASSWORD}
    env_file:
      - ./.env
    networks:
      - net
    depends_on:
      - sonarqube_postgres
    deploy:
      resources:
        limits:
          memory: 4g

  ###################################################################### OBSERVABILITY vs MONITORING ######################################################################
  # Prometheus
  prometheus:
    image: prometheus:latest
    build:
      context: ./configs/prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./configs/prometheus/promethues.yaml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ./logs/prometheus:/opt/bitnami/prometheus/data
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

  # Grafana
  grafana:
    image: grafana:latest
    build:
      context: ./configs/grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3030:3000"
    volumes:
      - ./logs/grafana:/var/lib/grafana
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

  # Loki
  loki:
    image: loki:latest
    build:
      context: ./configs/loki
      dockerfile: Dockerfile
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./configs/loki/local-loki.yaml:/etc/loki/local-config.yaml
      - ./logs/loki:/loki
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

  # Promtail
  promtail:
    image: promtail:latest
    build:
      context: ./configs/promtail
      dockerfile: Dockerfile
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./configs/promtail/config.yaml:/etc/promtail/config.yaml
      - ./logs/promtail/var/log:/var/log
    env_file:
      - ./.env
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  net:
    name: net
    driver: bridge
    external: true

# volumes:
#   mlflow_artifacts:

# Port note
# dagster 3001
# minio 9001
# mlflow 5000
# jupyter 8888
# jenkins 8080
# sonarqube 9095
# prometheus 9091
# grafana 3030
# loki 3100
# promtail 9080
