apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-model-app
  template:
    metadata:
      labels:
        app: api-model-app
    spec:
      containers:
      - name: api-model-container
        image: kyphan3802/api_model:latest
        ports:
        - containerPort: 7000
        env:
        # host.minikube.internal is the DNS name that allows pods running inside Minikube cluster to access services running on the host machine
        # This DNS name resolves to the IP address of the host machine, enabling communication between the Minikube cluster and the host's network services
        # In this case mlflow and minio container was already built then expose their port into host machine
        - name: MLFLOW_TRACKING_URI
          value: "http://host.minikube.internal:5000"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://host.minikube.internal:9000"
        envFrom:
        - configMapRef:
            name: api-model-config
