apiVersion: v1
kind: Service
metadata:
  name: api-model-service
spec:
  selector:
    app: api-model-app
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30000 # type: NodePort
  type: NodePort