# Define how to access and load the code
load_from:
  - grpc_server:
      host: pipeline
      port: 4000
      location_name: "pipeline"

  - grpc_server:
      host: mtl_pipeline
      port: 4001
      location_name: "mtl_pipeline"

  - grpc_server:
      host: training_pipeline
      port: 4002
      location_name: "training_pipeline"

  - grpc_server:
      host: model_serving
      port: 4003
      location_name: "model_serving"